query GetPlanTasks($tasksPlanId: ID, $tasksBucket: String) {
  tasks(planId: $tasksPlanId, bucket: $tasksBucket) {
    title
    id
    description
    participatorsLength
    participators {
      name
      avatar
    }
    commentsLength
    bucket
    status
    statusOptions
  }
}